
[project]
name = "user_management"
description = "User management API project"
version = "0.1.0"
requires-python = ">=3.8"
dependencies = [
	"fastapi",
	"uvicorn",
	"sqlalchemy",
	"pydantic",
	"passlib[bcrypt]"
]

[tool.uv]
# Optional: uv-specific settings can go here